//! Shell integration codegen for `scriv init`.
//!
//! The interactive shell layer — pick-and-`cd`, pick-and-edit, key bindings —
//! exists only because a child process cannot change its parent shell's
//! directory. Rather than hand-maintain that glue in the user's config, `scriv`
//! emits it, so it stays in lockstep with the CLI and ships completions too.

use clap::Command;
use clap_complete::Shell;

/// Render shell integration for `shell`, meant to be `source`d.
///
/// For fish this is the helper functions, a key-binding function, and
/// completions; for every other shell it is completions only (the pick-and-`cd`
/// helpers are fish-specific).
pub fn integration(shell: Shell, cmd: &mut Command) -> String {
    let mut out = String::new();

    if shell == Shell::Fish {
        out.push_str(FISH_FUNCTIONS);
        out.push_str("\n# --- completions ---\n");
    }

    let mut completions = Vec::new();
    clap_complete::generate(shell, cmd, cmd.get_name().to_string(), &mut completions);
    out.push_str(&String::from_utf8_lossy(&completions));

    out
}

/// The fish functions and key-binding helper.
///
/// Bindings are wrapped in a function the user calls from their own
/// `fish_user_key_bindings` rather than bound at source time, so they compose
/// with fish's binding lifecycle and leave the user's other bindings intact.
/// `pick` prints an absolute path, so the callers never re-expand `~`.
const FISH_FUNCTIONS: &str = r#"# scriv shell integration — generated by `scriv init fish`.
# Source this from config.fish, e.g. with:
#   scriv init fish | source

function scriv-repo-cd --description "Pick a repository and cd into it"
    set -l dir (command scriv repo pick)
    or return
    test -n "$dir"; and builtin cd $dir
end

# `scriv edit` spawns the editor itself — unlike cd, that needs no shell help —
# so these are thin wrappers kept only to hang key bindings off.
function scriv-edit --description "Pick a file under \$PWD and open it in \$EDITOR"
    command scriv edit
end

function scriv-file-edit --description "Pick a tracked file and open it in \$EDITOR"
    command scriv edit --tracked
end

# The find -> fuzzy-pick -> edit pipeline under the name it is usually aliased
# to. Arguments pass straight through, so `fe -t` and `fe path/to/file` work.
# This is the one unprefixed name scriv defines: redefine `fe` after sourcing
# if you already have one.
function fe --description "Find a file, fuzzy-pick it, open it in \$EDITOR"
    command scriv edit $argv
end

function scriv-branch-checkout --description "Pick a git branch and check it out"
    command scriv branch checkout
end

function scriv-pr-checkout --description "Pick a GitHub pull request and check it out"
    command scriv pr checkout
end

# Bindings use alt-<letter>, which fish leaves entirely unbound by default, and
# are chosen so the chord falls under one hand: alt-b (branch), alt-g (git) and
# alt-e (edit) are left-hand, alt-o and alt-p right-hand. Rebind any of them by
# calling `bind` yourself after `scriv_key_bindings`.
#
# Every binding ends in `commandline -f repaint`, never `execute`. The picker
# renders inline, and scriv opens it on a row of its own below the prompt so it
# never draws over one; `repaint` is what puts the command line back after a
# picker that took the whole screen, and what redraws a prompt whose contents
# the picked branch or directory has just changed. `execute` looks like it works
# only because submitting an empty command line prints a fresh prompt further
# down; with anything typed it runs the line, so pressing ctrl-o mid-command
# would execute whatever was there.
function scriv_key_bindings --description "Bind scriv pickers to keys"
    bind ctrl-o "scriv-repo-cd; commandline -f repaint"
    bind alt-o  "scriv-repo-cd; commandline -f repaint"
    bind alt-e  "scriv-edit; commandline -f repaint"
    bind f3     "scriv-file-edit; commandline -f repaint"
    bind alt-b  "scriv-branch-checkout; commandline -f repaint"
    bind alt-g  "scriv-branch-checkout; commandline -f repaint"
    bind alt-p  "scriv-pr-checkout; commandline -f repaint"
end
"#;

#[cfg(test)]
mod tests {
    use super::*;
    use clap::Arg;

    fn dummy() -> Command {
        Command::new("scriv").arg(Arg::new("verbose").long("verbose"))
    }

    #[test]
    fn fish_emits_helper_functions() {
        let out = integration(Shell::Fish, &mut dummy());
        assert!(out.contains("function scriv-repo-cd"));
        assert!(out.contains("function scriv-edit"));
        assert!(out.contains("function scriv-file-edit"));
        assert!(out.contains("function fe"));
        assert!(out.contains("function scriv-branch-checkout"));
        assert!(out.contains("function scriv-pr-checkout"));
        assert!(out.contains("function scriv_key_bindings"));
    }

    #[test]
    fn fish_emits_completions_and_keys() {
        let out = integration(Shell::Fish, &mut dummy());
        assert!(out.contains("complete -c scriv"));
        assert!(out.contains("bind ctrl-o"));
        assert!(out.contains("bind alt-o"));
        assert!(out.contains("bind alt-e"));
        assert!(out.contains("bind f3"));
        assert!(out.contains("bind alt-b"));
        assert!(out.contains("bind alt-g"));
        assert!(out.contains("bind alt-p"));
    }

    /// `fe` takes arguments, so it stands in for `scriv edit` completely rather
    /// than only its no-argument form.
    #[test]
    fn fe_forwards_arguments() {
        let out = integration(Shell::Fish, &mut dummy());
        assert!(out.contains("command scriv edit $argv"));
    }

    /// `fe` is deliberately the *only* unprefixed function scriv defines: every
    /// other helper is namespaced, so sourcing the integration cannot quietly
    /// shadow commands the user already has.
    #[test]
    fn fish_defines_one_unprefixed_function() {
        let out = integration(Shell::Fish, &mut dummy());
        let unprefixed: Vec<&str> = out
            .lines()
            .filter_map(|line| line.strip_prefix("function "))
            .filter_map(|rest| rest.split_whitespace().next())
            .filter(|name| !name.starts_with("scriv"))
            .collect();
        assert_eq!(unprefixed, vec!["fe"]);
    }

    /// `commandline -f execute` submits the command line, so a binding pressed
    /// with anything typed would run it — ctrl-o mid-`rm` is not a picker. It
    /// also leaves a stale prompt where a picked branch or directory has just
    /// changed what the prompt says. `repaint` is the fish idiom for both.
    #[test]
    fn bindings_repaint_rather_than_execute() {
        let out = integration(Shell::Fish, &mut dummy());
        assert!(
            !out.contains("commandline -f execute"),
            "a binding still submits the command line",
        );
        let binds: Vec<&str> = out
            .lines()
            .map(str::trim)
            .filter(|l| l.starts_with("bind "))
            .collect();
        assert!(!binds.is_empty(), "no bindings emitted");
        for bind in &binds {
            assert!(
                bind.contains("commandline -f repaint"),
                "binding does not repaint the prompt: {bind}",
            );
        }
    }

    /// f4 and f5 are common in user configs (awsvault, editors); fish leaves
    /// the whole alt-<letter> space free, so scriv stays out of the way.
    #[test]
    fn fish_avoids_function_keys_beyond_f3() {
        let out = integration(Shell::Fish, &mut dummy());
        assert!(!out.contains("bind f4"));
        assert!(!out.contains("bind f5"));
    }

    #[test]
    fn non_fish_emits_completions_only() {
        let out = integration(Shell::Bash, &mut dummy());
        assert!(out.contains("scriv")); // bash completion script mentions the command
        assert!(!out.contains("function scriv-repo-cd"));
    }
}
