//! Shell integration codegen for `scriv init`.
//!
//! The interactive shell layer — pick-and-`cd`, pick-and-edit, key bindings —
//! exists only because a child process cannot change its parent shell's
//! directory. Rather than hand-maintain that glue in the user's config, `scriv`
//! emits it, so it stays in lockstep with the CLI and ships completions too.

use clap::Command;
use clap_complete::Shell;

/// Render shell integration for `shell`, meant to be `source`d.
///
/// For fish this is the helper functions, a key-binding function, and
/// completions; for every other shell it is completions only (the pick-and-`cd`
/// helpers are fish-specific).
pub fn integration(shell: Shell, cmd: &mut Command) -> String {
    let mut out = String::new();

    if shell == Shell::Fish {
        out.push_str(FISH_FUNCTIONS);
        out.push_str("\n# --- completions ---\n");
    }

    let mut completions = Vec::new();
    clap_complete::generate(shell, cmd, cmd.get_name().to_string(), &mut completions);
    out.push_str(&String::from_utf8_lossy(&completions));

    out
}

/// The fish functions and key-binding helper.
///
/// Bindings are wrapped in a function the user calls from their own
/// `fish_user_key_bindings` rather than bound at source time, so they compose
/// with fish's binding lifecycle and leave the user's other bindings intact.
/// `pick` prints an absolute path, so the callers never re-expand `~`.
///
/// Every function here is namespaced `scriv-` except `fe` and `kl`, which are
/// the names those two pipelines are habitually aliased to and are worth
/// nothing under any other name. Redefine either after sourcing if it collides
/// with something already on the system.
const FISH_FUNCTIONS: &str = r#"# scriv shell integration — generated by `scriv init fish`.
# Source this from config.fish, e.g. with:
#   scriv init fish | source

function scriv-repo-cd --description "Pick a repository and cd into it"
    set -l dir (command scriv repo pick)
    or return
    test -n "$dir"; and builtin cd $dir
end

# Run a command as though it had been typed at the prompt, putting back whatever
# was already on the command line afterwards.
#
# This exists because of what `commandline -f repaint` does to output. A binding
# that prints something — a cd firing mise, direnv and fnox notices, a checkout
# printing git's "Switched to branch" — leaves the cursor below that output,
# while fish still believes the cursor is on the last row of its prompt. repaint
# redraws from where fish thinks it is, which is (prompt height - 1) rows above
# where the cursor actually is, and those rows are overwritten. A one-line prompt
# loses nothing and hides the whole problem; a two-line prompt silently eats the
# last line of every message, a three-line prompt the last two.
#
# Handing the command to fish instead means fish owns the output, and there is
# nothing to repaint over: the command is echoed, its output follows it, and a
# fresh prompt is drawn below. The cost is that the command lands in history,
# which is honest — it did run.
#
# The command line is stashed and put back because `execute` submits whatever is
# on it. Without that, reaching for a picker half-way through typing something
# would run the half-typed thing.
function scriv-run-as-command --description "Run a command as if it had been typed"
    set -g __scriv_stashed_commandline (commandline)
    set -g __scriv_stashed_cursor (commandline --cursor)
    commandline --replace -- "$argv"
    commandline -f execute
end

function scriv-restore-command-line --on-event fish_postexec
    set -q __scriv_stashed_commandline; or return
    commandline --replace -- $__scriv_stashed_commandline
    commandline --cursor $__scriv_stashed_cursor
    set -e __scriv_stashed_commandline
    set -e __scriv_stashed_cursor
end

# Unlike cd, opening a browser needs no shell help — this is a thin wrapper, so
# that a key binding has one name to hand fish rather than a command line to
# quote.
function scriv-repo-open --description "Open this repository on GitHub, or pick one"
    command scriv repo open
end

# `scriv edit` spawns the editor itself — unlike cd, that needs no shell help —
# so these are thin wrappers for the same reason as the one above.
function scriv-edit --description "Pick a file under \$PWD and open it in \$EDITOR"
    command scriv edit
end

function scriv-file-edit --description "Pick a tracked file and open it in \$EDITOR"
    command scriv edit --tracked
end

# The find -> fuzzy-pick -> edit pipeline under the name it is usually aliased
# to. Arguments pass straight through, so `fe -t` and `fe path/to/file` work.
function fe --description "Find a file, fuzzy-pick it, open it in \$EDITOR"
    command scriv edit $argv
end

# `scriv proc kill` under the name it is usually aliased to, and with the signal
# that name implies: `kl` is reached for when something is already wedged and
# has stopped answering, so it sends KILL. `scriv proc kill` on its own sends
# the catchable TERM, which is the right default for a command spelled out in
# full. Arguments pass straight through, so `kl 1234` works.
function kl --description "Fuzzy-pick running processes and kill them"
    command scriv proc kill --force $argv
end

function scriv-branch-checkout --description "Pick a git branch and check it out"
    command scriv branch checkout
end

function scriv-pr-checkout --description "Pick a GitHub pull request and check it out"
    command scriv pr checkout
end

# History is the one picker whose result belongs on the command line rather than
# run outright, and only the shell can write there — so unlike the editor
# wrappers above, this one is doing real work.
#
# NUL on both sides of the pipe: a history entry can be a multi-line command,
# and a newline-terminated one read back through `(...)` would be split into
# separate arguments and rejoined with spaces, quietly turning it into a command
# that was never run.
#
# The query is quoted for the same reason in the other direction. Bare
# `(commandline)` is a list, and on an empty command line it is a list of *two*
# empty strings — one argument too many, which `scriv history pick` rejects
# outright. `"$(...)"` is fish's one-argument form: the whole command line,
# newlines and all, or one empty string when there is nothing typed yet.
function scriv-history-pick --description "Fuzzy-pick a past command onto the command line"
    command scriv history pick --print0 --query "$(commandline)" | read --local --null picked
    and commandline --replace -- $picked
end

# `up` reaches the picker only where fish would have gone to history anyway.
# Inside the completion pager, and on any line of a multi-line command but the
# first, up still means "move up" — taking that away would make a multi-line
# command impossible to edit and the pager impossible to walk.
#
# `up-line` is what fish binds `up` to, so handing control back to it is exactly
# "do what would have happened". It is not `up-or-search`: that is a shell
# function rather than an input function in fish 4, and `commandline -f` refuses
# it — quietly, from inside a key binding, where nobody sees the error until
# they are three lines into editing a command.
function scriv-history-up --description "Search history, or move up within a multi-line command"
    if commandline --paging-mode; or test (commandline --line) -gt 1
        commandline -f up-line
        return
    end
    scriv-history-pick
end

# Bindings are ctrl-<letter> where a ctrl chord is free, reachable without
# leaving the home row on a layout where ctrl sits under the left pinky. Only
# ctrl-o and ctrl-q are unbound in fish, so ctrl-g displaces a preset binding on
# purpose: branch checkout, over `cancel` — escape and ctrl-c both do that too.
#
# ctrl-r and up displace fish's own history keys — `history-pager` and
# `up-line` — and are the two bindings here that replace something people
# press constantly. That is the point of them rather than a cost: both land on
# the same history, searched fuzzily instead of by prefix, and both put the
# command back on the line to be read before it runs. `up` keeps fish's
# behaviour wherever the picker would be wrong (see scriv-history-up), and
# ctrl-p/ctrl-n are left alone as `up-line`/`down-line`, so walking a one-line
# prompt back through history one entry at a time is still there for anyone who
# wants it.
#
# The function keys displace nothing: fish binds none of f1-f12 itself. f1 and f3
# sit at the low end that users' own tools tend to leave alone; f4 and f5 are
# where those tools cluster (awsvault, editors), so the third one skips past them
# to f7. They carry the pickers reached least often, since a function key is a
# longer reach than a ctrl chord.
#
# Rebind any of them by calling `bind` yourself after `scriv_key_bindings`; the
# last binding for a key wins. alt-<letter> is left alone on purpose — it looks
# free but is not, since fish presets alt-b, alt-e, alt-o and alt-p among others.
#
# A binding either produces output or writes to the command line, and the two
# need opposite treatment.
#
# The pickers that *act* — cd somewhere, check something out, open an editor —
# print as they go, and their output has to survive. They go through
# scriv-run-as-command, which hands the command to fish so fish owns the
# output; see the comment there for what `repaint` does to it otherwise.
#
# The history pickers produce no output at all: they put a command on the line
# for the user to read before running it. `repaint` is exactly right for that,
# and running them through the command line instead would submit the command
# they had just finished not submitting.
#
# `execute` is only safe here because scriv-run-as-command stashes the command
# line first. Bound directly it would submit whatever was typed, so pressing
# ctrl-o half-way through an `rm` would run it.
function scriv_key_bindings --description "Bind scriv pickers to keys"
    bind ctrl-o "scriv-run-as-command scriv-repo-cd"
    bind ctrl-q "scriv-run-as-command scriv-edit"
    bind f1     "scriv-run-as-command scriv-repo-open"
    bind f3     "scriv-run-as-command scriv-file-edit"
    bind ctrl-g "scriv-run-as-command scriv-branch-checkout"
    bind f7     "scriv-run-as-command scriv-pr-checkout"
    bind ctrl-r "scriv-history-pick; commandline -f repaint"
    bind up     "scriv-history-up; commandline -f repaint"
end
"#;

#[cfg(test)]
mod tests {
    use super::*;
    use clap::Arg;

    fn dummy() -> Command {
        Command::new("scriv").arg(Arg::new("verbose").long("verbose"))
    }

    #[test]
    fn fish_emits_helper_functions() {
        let out = integration(Shell::Fish, &mut dummy());
        assert!(out.contains("function scriv-repo-cd"));
        assert!(out.contains("function scriv-run-as-command"));
        assert!(out.contains("function scriv-restore-command-line"));
        assert!(out.contains("function scriv-repo-open"));
        assert!(out.contains("function scriv-edit"));
        assert!(out.contains("function scriv-file-edit"));
        assert!(out.contains("function fe"));
        assert!(out.contains("function kl"));
        assert!(out.contains("function scriv-branch-checkout"));
        assert!(out.contains("function scriv-pr-checkout"));
        assert!(out.contains("function scriv-history-pick"));
        assert!(out.contains("function scriv-history-up"));
        assert!(out.contains("function scriv_key_bindings"));
    }

    #[test]
    fn fish_emits_completions_and_keys() {
        let out = integration(Shell::Fish, &mut dummy());
        assert!(out.contains("complete -c scriv"));
        assert!(out.contains("bind ctrl-o"));
        assert!(out.contains("bind ctrl-q"));
        assert!(out.contains("bind f1"));
        assert!(out.contains("bind f3"));
        assert!(out.contains("bind f7"));
        assert!(out.contains("bind ctrl-g"));
        assert!(out.contains("bind ctrl-r"));
        assert!(out.contains("bind up"));
    }

    /// A history entry can be a multi-line command. Read back through fish's
    /// ordinary `(...)` substitution it would be split on those newlines and
    /// rejoined with spaces — a command the user never ran, handed to them
    /// looking like one they did. NUL on both sides is what prevents it.
    #[test]
    fn history_travels_nul_terminated() {
        let out = integration(Shell::Fish, &mut dummy());
        assert!(out.contains("history pick --print0"), "{out}");
        assert!(out.contains("read --local --null picked"), "{out}");
    }

    /// The query must reach scriv as exactly one argument. Bare `(commandline)`
    /// is a *list*, and on an empty command line — by far the common way to
    /// reach this picker — fish expands it to two empty strings, one argument
    /// more than `history pick` accepts, so ctrl-r fails before the picker
    /// opens. Only fish's quoted `"$(...)"` form is one argument every time.
    #[test]
    fn the_query_reaches_scriv_as_one_argument() {
        let out = integration(Shell::Fish, &mut dummy());
        assert!(out.contains(r#"--query "$(commandline)""#), "{out}");
    }

    /// `up` is fish's own key, and the picker is only an improvement where fish
    /// would have gone to history anyway. On the second line of a multi-line
    /// command, up has to still move the cursor up — a picker there would make
    /// such a command uneditable.
    #[test]
    fn up_falls_through_to_fish_where_the_picker_would_be_wrong() {
        let out = integration(Shell::Fish, &mut dummy());
        assert!(out.contains("commandline --paging-mode"), "{out}");
        assert!(out.contains("commandline --line) -gt 1"), "{out}");
    }

    /// The fallthrough has to name an *input* function. `up-or-search` reads
    /// like the right answer and is a shell function in fish 4, which
    /// `commandline -f` rejects — from inside a key binding, so the failure
    /// only shows up once someone is editing a multi-line command. `up-line` is
    /// what fish binds `up` to itself.
    #[test]
    fn up_hands_back_to_fishs_own_input_function() {
        let out = integration(Shell::Fish, &mut dummy());
        assert!(out.contains("commandline -f up-line"), "{out}");
        assert!(
            !out.contains("-f up-or-search"),
            "up-or-search is not an input function in fish 4",
        );
    }

    /// fish binds most of alt-<letter> itself — alt-b is backward-word, alt-e
    /// opens the command line in `$EDITOR`, alt-o pages the file at the cursor,
    /// alt-p pipes the job through the pager — so scriv taking any of it would
    /// quietly replace a binding the user did not ask it to touch.
    #[test]
    fn fish_leaves_alt_alone() {
        let out = integration(Shell::Fish, &mut dummy());
        let alt: Vec<&str> = out
            .lines()
            .map(str::trim)
            .filter(|l| l.starts_with("bind alt-"))
            .collect();
        assert!(alt.is_empty(), "scriv binds alt keys: {alt:?}");
    }

    /// Historic control codes: ctrl-i *is* tab, ctrl-j newline and ctrl-m enter.
    /// Terminals that speak a modern key encoding can tell them apart, but on
    /// the ones that cannot, binding these breaks completion or the enter key.
    #[test]
    fn fish_avoids_keys_that_collide_with_tab_and_enter() {
        let out = integration(Shell::Fish, &mut dummy());
        for key in ["bind ctrl-i", "bind ctrl-j", "bind ctrl-m"] {
            assert!(!out.contains(key), "{key} collides with tab or enter");
        }
    }

    /// `fe` takes arguments, so it stands in for `scriv edit` completely rather
    /// than only its no-argument form.
    #[test]
    fn fe_forwards_arguments() {
        let out = integration(Shell::Fish, &mut dummy());
        assert!(out.contains("command scriv edit $argv"));
    }

    /// `fe` and `kl` are deliberately the *only* unprefixed functions scriv
    /// defines: every other helper is namespaced, so sourcing the integration
    /// cannot quietly shadow commands the user already has. Both earn it by
    /// being the names their pipelines are habitually aliased to.
    #[test]
    fn fish_defines_only_the_two_habitual_aliases_unprefixed() {
        let out = integration(Shell::Fish, &mut dummy());
        let unprefixed: Vec<&str> = out
            .lines()
            .filter_map(|line| line.strip_prefix("function "))
            .filter_map(|rest| rest.split_whitespace().next())
            .filter(|name| !name.starts_with("scriv"))
            .collect();
        assert_eq!(unprefixed, vec!["fe", "kl"]);
    }

    /// `kl` is the wedged-process key, so it has to carry `--force`: reaching
    /// for it and getting a signal the process is already ignoring is the one
    /// way for it to be useless.
    #[test]
    fn kl_sends_the_uncatchable_signal() {
        let out = integration(Shell::Fish, &mut dummy());
        assert!(
            out.contains("command scriv proc kill --force $argv"),
            "{out}"
        );
    }

    /// A binding that prints something cannot end in `commandline -f repaint`.
    /// fish redraws the prompt from where it believes the cursor is — the last
    /// row of the prompt — while the cursor is actually below whatever was
    /// printed, so the redraw overwrites (prompt height - 1) rows of it. On a
    /// one-line prompt nothing is lost, which is what hid this; on a two-line
    /// prompt every mise, direnv or git message loses its last line.
    ///
    /// Handing the command to fish is what fixes it: fish echoes it, its output
    /// follows, and the new prompt is drawn below all of it.
    #[test]
    fn bindings_that_produce_output_run_through_the_command_line() {
        let out = integration(Shell::Fish, &mut dummy());
        for key in ["ctrl-o", "ctrl-q", "f1", "f3", "ctrl-g", "f7"] {
            let bind = binding_for(&out, key);
            assert!(
                bind.contains("scriv-run-as-command"),
                "{key} repaints over the output it produces: {bind}",
            );
        }
    }

    /// The history pickers print nothing — they put a command on the line to be
    /// read before it runs. Running *them* through the command line would
    /// submit the very command the user had not submitted yet.
    #[test]
    fn the_history_bindings_still_repaint() {
        let out = integration(Shell::Fish, &mut dummy());
        for key in ["ctrl-r", "up"] {
            let bind = binding_for(&out, key);
            assert!(
                bind.contains("commandline -f repaint"),
                "{key} does not repaint: {bind}",
            );
            assert!(
                !bind.contains("scriv-run-as-command"),
                "{key} would submit the command it just picked: {bind}",
            );
        }
    }

    /// `execute` submits whatever is on the command line, so the stash is not a
    /// nicety: without it, reaching for a picker half-way through typing `rm
    /// -rf …` would run it.
    #[test]
    fn the_typed_command_line_is_stashed_before_executing_and_put_back_after() {
        let out = integration(Shell::Fish, &mut dummy());
        let stash = out
            .split("function scriv-run-as-command")
            .nth(1)
            .expect("no scriv-run-as-command");
        let stash = stash.split("\nend").next().unwrap();
        let saves = stash.find("set -g __scriv_stashed_commandline");
        let executes = stash.find("commandline -f execute");
        assert!(
            matches!((saves, executes), (Some(s), Some(e)) if s < e),
            "the command line is not saved before it is submitted:\n{stash}",
        );
        assert!(
            out.contains("--on-event fish_postexec"),
            "nothing puts the command line back",
        );
        assert!(
            out.contains("commandline --cursor $__scriv_stashed_cursor"),
            "the cursor is not put back where it was",
        );
    }

    /// The line `bind <key> …` for `key`.
    fn binding_for<'a>(out: &'a str, key: &str) -> &'a str {
        out.lines()
            .map(str::trim)
            .find(|l| l.starts_with(&format!("bind {key} ")))
            .unwrap_or_else(|| panic!("no binding for {key}"))
    }

    /// f4 and f5 are where users' own tools cluster (awsvault, editors), so scriv
    /// steps over them rather than reaching for the next free key upwards.
    #[test]
    fn fish_avoids_the_crowded_function_keys() {
        let out = integration(Shell::Fish, &mut dummy());
        assert!(!out.contains("bind f4"));
        assert!(!out.contains("bind f5"));
    }

    /// ctrl-p/ctrl-n are fish's `up-line`/`down-line`. scriv takes `up` for the
    /// history picker, so these are what is left of walking history one entry at
    /// a time on a one-line prompt — taking them too would remove the fallback
    /// as well as the default.
    #[test]
    fn fish_leaves_history_navigation_alone() {
        let out = integration(Shell::Fish, &mut dummy());
        assert!(!out.contains("bind ctrl-p"), "ctrl-p is up-line");
        assert!(!out.contains("bind ctrl-n"), "ctrl-n is down-line");
    }

    #[test]
    fn non_fish_emits_completions_only() {
        let out = integration(Shell::Bash, &mut dummy());
        assert!(out.contains("scriv")); // bash completion script mentions the command
        assert!(!out.contains("function scriv-repo-cd"));
    }
}
